// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    "@nuxt/icon",
    "@nuxtjs/tailwindcss",
    "@nuxtjs/i18n",
    "@nuxtjs/sitemap",
  ],

  devtools: { enabled: true },

  app: {
    pageTransition: {
      name: "page",
      mode: "out-in",
    },
    head: {
      link: [
        {
          rel: "icon",
          href: "/favicon.ico",
        },
        {
          rel: "apple-touch-icon",
          sizes: "180x180",
          href: "/apple-touch-icon.png",
        },
      ],
    },
  },

  site: {
    url: "https://localsend.org",
  },

  i18n: {
    baseUrl: "https://localsend.org",
    strategy: "prefix_except_default",
    defaultLocale: "en",
    pages: {
      privacy: false,
      terms: false,
      imprint: false,
      contact: false,
      news: false,
    },
    locales: [
      {
        code: "ar",
        language: "ar-AR",
        file: "ar.json",
        name: "العربية",
        englishName: "Arabic",
        dir: "rtl",
      },
      {
        code: "bn",
        language: "bn-BD",
        file: "bn.json",
        name: "বাংলা",
        englishName: "Bengali",
      },
      {
        code: "ca",
        language: "ca-ES",
        file: "ca.json",
        name: "Català",
        englishName: "Catalan",
      },
      {
        code: "ckb",
        language: "ckb",
        file: "ckb.json",
        name: "کوردی ناوەندی",
        englishName: "Central Kurdish",
        dir: "rtl",
      },
      {
        code: "cs",
        language: "cs-CZ",
        file: "cs.json",
        name: "Čeština",
        englishName: "Czech",
      },
      {
        code: "de",
        language: "de-DE",
        file: "de.json",
        name: "Deutsch",
        englishName: "German",
      },
      {
        code: "el",
        language: "el-GR",
        file: "el.json",
        name: "Ελληνικά",
        englishName: "Greek",
      },
      {
        code: "en",
        language: "en-US",
        file: "en.json",
        name: "English",
        englishName: "English",
        isCatchallLocale: true,
      },
      {
        code: "es",
        language: "es-ES",
        file: "es.json",
        name: "Español",
        englishName: "Spanish",
      },
      {
        code: "et",
        language: "et-EE",
        file: "et.json",
        name: "Eesti",
        englishName: "Estonian",
      },
      {
        code: "fa",
        language: "fa-IR",
        file: "fa.json",
        name: "فارسی",
        englishName: "Persian",
        dir: "rtl",
      },
      {
        code: "fil",
        language: "fil-PH",
        file: "fil.json",
        name: "Filipino",
        englishName: "Filipino",
      },
      {
        code: "fr",
        language: "fr-FR",
        file: "fr.json",
        name: "Français",
        englishName: "French",
      },
      {
        code: "gl",
        language: "gl-ES",
        file: "gl.json",
        name: "Galego",
        englishName: "Galician",
      },
      {
        code: "he",
        language: "he-IL",
        file: "he.json",
        name: "עברית",
        englishName: "Hebrew",
        dir: "rtl",
      },
      {
        code: "hi",
        language: "hi-IN",
        file: "hi.json",
        name: "हिन्दी",
        englishName: "Hindi",
      },
      {
        code: "id",
        language: "id-ID",
        file: "id.json",
        name: "Bahasa Indonesia",
        englishName: "Indonesian",
      },
      {
        code: "it",
        language: "it-IT",
        file: "it.json",
        name: "Italiano",
        englishName: "Italian",
      },
      {
        code: "ja",
        language: "ja-JP",
        file: "ja.json",
        name: "日本語",
        englishName: "Japanese",
      },
      {
        code: "ka",
        language: "ka-IN",
        file: "ka.json",
        name: "ಕನ್ನಡ",
        englishName: "Kannada",
      },
      {
        code: "km",
        language: "km-KH",
        file: "km.json",
        name: "ភាសាខ្មែរ",
        englishName: "Khmer",
      },
      {
        code: "ko",
        language: "ko-KR",
        file: "ko.json",
        name: "한국어",
        englishName: "Korean",
      },
      {
        code: "mal-IN",
        language: "mal-IN",
        file: "mal-IN.json",
        name: "മലയാളം",
        englishName: "Malayalam",
      },
      {
        code: "mr",
        language: "mr-IN",
        file: "mr.json",
        name: "मराठी",
        englishName: "Marathi",
      },
      {
        code: "nl",
        language: "nl-NL",
        file: "nl.json",
        name: "Nederlands",
        englishName: "Dutch",
      },
      {
        code: "oc",
        language: "oc-FR",
        file: "oc.json",
        name: "Occitan",
        englishName: "Occitan",
      },
      {
        code: "pl",
        language: "pl-PL",
        file: "pl.json",
        name: "Polski",
        englishName: "Polish",
      },
      {
        code: "pt-BR",
        language: "pt-BR",
        file: "pt-BR.json",
        name: "Português (Brasil)",
        englishName: "Portuguese (Brazil)",
      },
      {
        code: "pt-PT",
        language: "pt-PT",
        file: "pt-PT.json",
        name: "Português (Portugal)",
        englishName: "Portuguese (Portugal)",
      },
      {
        code: "ru",
        language: "ru-RU",
        file: "ru.json",
        name: "Русский",
        englishName: "Russian",
      },
      {
        code: "sk",
        language: "sk-SK",
        file: "sk.json",
        name: "Slovenčina",
        englishName: "Slovak",
      },
      {
        code: "sr",
        language: "sr-RS",
        file: "sr.json",
        name: "Srpski (latinica)",
        englishName: "Serbian (Latin)",
      },
      {
        code: "sr-Cyrl",
        language: "sr-RS",
        file: "sr-Cyrl.json",
        name: "Српски (ћирилица)",
        englishName: "Serbian (Cyrillic)",
      },
      {
        code: "sv",
        language: "sv-SE",
        file: "sv.json",
        name: "Svenska",
        englishName: "Swedish",
      },
      {
        code: "ta",
        language: "ta-IN",
        file: "ta.json",
        name: "தமிழ்",
        englishName: "Tamil",
      },
      {
        code: "te",
        language: "te-IN",
        file: "te.json",
        name: "తెలుగు",
        englishName: "Telugu",
      },
      {
        code: "th",
        language: "th-TH",
        file: "th.json",
        name: "ภาษาไทย",
        englishName: "Thai",
      },
      {
        code: "tr",
        language: "tr-TR",
        file: "tr.json",
        name: "Türkçe",
        englishName: "Turkish",
      },
      {
        code: "ug",
        language: "ug-CN",
        file: "ug.json",
        name: "ئۇيغۇرچە",
        englishName: "Uyghur",
        dir: "rtl",
      },
      {
        code: "uk",
        language: "uk-UA",
        file: "uk.json",
        name: "Українська",
        englishName: "Ukrainian",
      },
      {
        code: "vi",
        language: "vi-VN",
        file: "vi.json",
        name: "Tiếng Việt",
        englishName: "Vietnamese",
      },
      {
        code: "zh-CN",
        language: "zh-CN",
        file: "zh-CN.json",
        name: "简体中文",
        englishName: "Chinese (Simplified)",
      },
      {
        code: "zh-HK",
        language: "zh-HK",
        file: "zh-HK.json",
        name: "繁體中文 – 香港",
        englishName: "Chinese (Hong Kong)",
      },
      {
        code: "zh-TW",
        language: "zh-TW",
        file: "zh-TW.json",
        name: "繁體中文 – 台灣",
        englishName: "Chinese (Taiwan)",
      },
    ],
  },

  nitro: {
    prerender: {
      autoSubfolderIndex: false,
    },
  },

  // https://stackoverflow.com/questions/67703133/how-to-use-env-variables-in-nuxt-2-or-3
  vite: {
    define: {
      'process.env.IMPRINT_STREET': JSON.stringify(process.env.IMPRINT_STREET),
      'process.env.IMPRINT_CITY': JSON.stringify(process.env.IMPRINT_CITY),
    }
  },

  compatibilityDate: "2024-10-20",
});
